name: iOS Build (No Code Signing)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app

    - name: Resolve Swift Package dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Build the app (no code signing)
      run: |
        xcodebuild clean build \
          -project YourApp.xcodeproj \
          -scheme YourAppScheme \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGNING_ALLOWED=NO
