name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14  # You can also use macos-13 or macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby (for CocoaPods, if needed)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install CocoaPods dependencies
      run: |
        gem install cocoapods
        pod install
      working-directory: ./Pocket-Contacts-Pro  # Update this if needed

    - name: Build the app
      run: |
        xcodebuild -workspace YourApp.xcworkspace \
                   -scheme YourAppScheme \
                   -sdk iphonesimulator \
                   -destination 'platform=iOS Simulator,name=iPhone 15' \
                   clean build
