name: iOS Native Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14  # macOS runner with Xcode pre-installed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app  # Adjust version if needed

    - name: Install dependencies (if using Swift Package Manager)
      run: xcodebuild -resolvePackageDependencies

    - name: Build the app
      run: |
        xcodebuild clean build \
          -project YourApp.xcodeproj \
          -scheme YourAppScheme \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
